orderpack: m_sets Module Reference
m_sets Module Reference
Functions/Subroutines
integer function, dimension(:), allocatable, public unique (A, setOrder)
integer function, dimension(:), allocatable, public union (A, B, setOrder)
integer function, dimension(:), allocatable, public intersect (A, B, setOrder)
integer function, dimension(:), allocatable, public setdiff (A, B, setOrder)
integer function, dimension(:), allocatable, public ismember (A, B)
integer function, dimension(:), allocatable, public setxor (A, B, setOrder)
Function/Subroutine Documentation
intersect()
integer function, dimension(:), allocatable, public m_sets::intersect (integer, dimension(:), intent(in) A, integer, dimension(:), intent(in) B, character(len=*), intent(in), optional setOrder)
 ! C = intersect(A,B) returns the data common to both A and B, with no repetitions. C is in sorted order by default
 integer, intent(in)                    :: A(:)
 integer, intent(in)                    :: B(:)
 character(len=*), intent(in), optional :: setOrder
 integer, allocatable                   :: result(:)
 integer, allocatable                   :: iwrk(:)
    result = [unique(a, setorder), unique(b, setorder)]
    if (allocated(iwrk)) deallocate (iwrk)
    allocate (iwrk(size(result)))
    call occurrences_(result, iwrk)
    result = unique(pack(result, iwrk .gt. 1), setorder)
References unique().
ismember()
integer function, dimension(:), allocatable, public m_sets::ismember (integer, dimension(:), intent(in) A, integer, dimension(:), intent(in) B)
 ! C = ismember(A,B) returns an array containing 1 (true) where the data in A is found in B. Elsewhere, the array contains 0
 integer, intent(in)   :: a(:)
 integer, intent(in)   :: b(:)
 integer, allocatable  :: result(:)
 integer, allocatable  :: iwrk1(:)
 integer, allocatable  :: iwrk2(:)
 integer               :: inums
    inums=size(a)
    result = [ a, unique(b) ] ! potentially a lot of memory
    if (allocated(iwrk2)) deallocate (iwrk2)
    allocate (iwrk2(size(a)))
    if (allocated(iwrk1)) deallocate (iwrk1)
    allocate (iwrk1(size(result)))
    call occurrences_(result, iwrk1)
    call occurrences_(a, iwrk2)
    result=iwrk1(:inums)-iwrk2
    result=merge(0,1,result.eq.0)
References unique().
setdiff()
integer function, dimension(:), allocatable, public m_sets::setdiff (integer, dimension(:), intent(in) A, integer, dimension(:), intent(in) B, character(len=*), intent(in), optional setOrder)
 ! C = setdiff(A,B) returns the data in A that is not in B, with no repetitions. C is in sorted order by default.
 integer, intent(in)                    :: a(:)
 integer, intent(in)                    :: b(:)
 character(len=*), intent(in), optional :: setOrder
 integer, allocatable                   :: result(:)
 integer, allocatable                   :: iwrk(:)
    result = unique(b, setorder='stable')
    result = [unique(a, setorder='stable'), result, result] ! potentially a lot of memory
    if (allocated(iwrk)) deallocate (iwrk)
    allocate (iwrk(size(result)))
    call occurrences_(result, iwrk)
    result = unique(pack(result, iwrk .eq. 1), setorder)
References unique().
setxor()
integer function, dimension(:), allocatable, public m_sets::setxor (integer, dimension(:), intent(in) A, integer, dimension(:), intent(in) B, character(len=*), intent(in), optional setOrder)
 ! C = setxor(A,B,setOrder) returns the data of A and B that are not in their intersection
 !                          (the symmetric difference), with no repetitions. That is, setxor returns the
 !                          data that occurs in A or B, but not both. C is in sorted order.
 integer, intent(in)                    :: a(:)
 integer, intent(in)                    :: b(:)
 character(len=*), intent(in), optional :: setOrder
 integer, allocatable                   :: result(:)
 integer, allocatable                   :: iwrk1(:)
 integer, allocatable                   :: iwrk2(:)
 integer, allocatable                   :: iwrk3(:)
 integer                                :: inums
    inums=size(a)
    result = [ a, b ] ! potentially a lot of memory
    if (allocated(iwrk1)) deallocate (iwrk1)
    allocate (iwrk1(size(result)))
    call occurrences_(result, iwrk1)
    if (allocated(iwrk2)) deallocate (iwrk2)
    allocate (iwrk2(size(a)))
    call occurrences_(a, iwrk2)
    if (allocated(iwrk3)) deallocate (iwrk3)
    allocate (iwrk3(size(b)))
    call occurrences_(b, iwrk3)
    iwrk1=iwrk1-[iwrk2,iwrk3]
    result=pack(result,iwrk1.eq.0)
    result=unique(result,setorder)
References unique().
union()
integer function, dimension(:), allocatable, public m_sets::union (integer, dimension(:), intent(in) A, integer, dimension(:), intent(in) B, character(len=*), intent(in), optional setOrder)
 ! C = union(A,B) returns the combined data from A and B with no repetitions. C is in sorted order.
 integer, intent(in)                    :: A(:)
 integer, intent(in)                    :: B(:)
 character(len=*), intent(in), optional :: setOrder
 integer, allocatable                   :: result(:)
    result = unique([a, b], setorder)
References unique().
unique()
integer function, dimension(:), allocatable, public m_sets::unique (integer, dimension(:), intent(in) A, character(len=*), intent(in), optional setOrder)
 ! C = unique(A) returns the same data as in A, but with no repetitions. C is in sorted order.
 integer, intent(in)                    :: A(:)
 character(len=*), intent(in), optional :: setOrder
 integer, allocatable                   :: result(:)
 character(len=:), allocatable          :: setOrder_
 integer                                :: nuni
    if (present(setorder)) then
       setorder_ = setorder
    else
       setorder_ = 'sorted'
    end if
    result = a
    select case (setorder_)
    case ('stable')
       call unique_(result, nuni)
       result = result(:nuni)
    case ('sorted')
       if (allocated(result)) deallocate (result)
       allocate (result(size(a)))
       call rank_unique_(a, result, nuni)
       result = a(result(:nuni))
    case default
       stop '*unique* unknown setOrder '//setorder_
    end select